SPACEMAP-WEB/spacemap-platform

package-lock.json, src/app.components/common/MainLayout.tsx, src/app.components/common/SideMenu.tsx, src/app.components/common/Table.tsx, src/app.components/launchConjunctions/AssessmentModal.tsx, src/app.components/launchConjunctions/LPDBTable.tsx, src/app.components/launchConjunctions/index.tsx, src/app.feature/conjunctions/query/useMutationLPDB.ts, src/app.feature/conjunctions/query/useQueryLPDB.ts, src/app.modules/keyFactory.ts, src/app.modules/types/launchConjunctions.ts
기능 구현
1. 테이블 띄우는 거 데이터 유무에 따른 분기처리
2. 테이블 퍼블리싱
3. API GET POST 통신
=> feat: launch conjunctions modal and functions

package.json, src/app.components/common/MainLayout.tsx, src/app.feature/conjunctions/component/ConjuctionsTable.tsx, src/app.feature/conjunctions/screen/Conjunctions.tsx, src/app.feature/favorite/component/ConjuctionsFavroiteTable.tsx, src/app.feature/favorite/query/useMutationFavorite.ts, src/app.feature/favorite/query/useQueryFavorite.ts, src/app.feature/favorite/screen/ConjuctionsFavorite.tsx
1. 즐겨찾기 추가하고 favorite 클릭시 안되는 에러 수정
2. 즐겨찾기 추가시 실시간으로 favorite 컨정션 변경
=> feat(publishing) : 즐겨찾기 관련 에러 수정

src/app.feature/launchConjunctions/LPDBDetailTable.tsx, src/app.feature/launchConjunctions/module/lpdbDataRefactor.ts, src/app.feature/launchConjunctions/module/useInstance.ts, src/app.feature/launchConjunctions/query/useQueryLPDB.ts, src/app.modules/types/launchConjunctions.ts
lpdb DONE 버튼 클릭시 디테일 화면 테이블 구현
=> feat: implement lpdb sub table

src/app.feature/conjunctions/module/keyFrames.ts, src/app.feature/conjunctions/screen/Conjunctions.tsx
=> feat(animation)

package.json, src/app.feature/launchConjunctions/AssessmentModal.tsx, src/app.feature/launchConjunctions/LcaAlertModal.tsx, src/app.feature/launchConjunctions/module/dateHandle.ts
=> feat(lca403) lca안되는 시간대 모달 추가

src/app.feature/launchConjunctions/components/LPDBDetailTable.tsx, src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx
=> fix: fix infinite loop

src/app.components/MainLayout.tsx, src/app.components/button/Button.tsx, src/app.components/button/LoginButton.tsx, src/app.feature/launchConjunctions/components/AssessmentModal.tsx, src/app.feature/watcherCatcher/components/SearchModal.tsx, src/app.feature/watcherCatcher/types/watcherCatcher.ts
1. 버튼 컴포넌트화
2. UTCdate로 변경해서 서버로 보내는 로직
=> fix: fix button component and UTC date

src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx, src/app.feature/watcherCatcher/components/WCDBTable.tsx
=> fix: fix accessor error

src/app.components/button/Button.tsx, src/app.components/button/LoginButton.tsx, src/app.feature/conjunctions/hooks/useConjunctionsEventHandler.ts, src/app.feature/conjunctions/screen/Conjunctions.tsx, src/app.feature/favorites/component/FavoritesSubscription.tsx, src/app.feature/favorites/screen/Favorites.tsx, src/app.feature/launchConjunctions/components/LPDBTable.tsx, src/app.feature/launchConjunctions/screen/LaunchConjunctions.tsx, src/app.feature/sideMenu/screen/SideMenu.tsx, src/app.feature/watcherCatcher/components/WCDBTable.tsx
버튼 반응형
애니메이션 수정
conjunctions event 함수 분리
=> fix: refactoring codes

src/app.feature/conjunctions/component/TableColumns.tsx, src/app.feature/favorites/component/FavoritesSubscriptionTable.tsx, src/app.feature/favorites/component/FavoritesTable.tsx, src/app.feature/favorites/query/useMutationFavorite.ts, src/app.feature/favorites/screen/Favorites.tsx, src/app.feature/favorites/types/favorite.ts
=> feat: favorite mailing service

src/app.feature/conjunctions/component/ConjunctionsTable.tsx, src/app.feature/conjunctions/component/TableColumns.tsx, src/app.feature/favorites/component/FavoritesTable.tsx, src/app.feature/favorites/component/TableColumns.tsx, src/app.feature/launchConjunctions/components/LPDBDetailTable.tsx, src/app.store/cesium/cesiumReducer.ts, src/app.store/cesium/store.cesium.ts, src/app.store/cesium/type.ts, src/app.store/config/configureStore.ts
=> 컨정션 세슘 에러 해결

src/app.components/Logo.tsx, src/app.components/button/LoginButton.tsx, src/app.modules/cesium/drawCzml.ts, src/app.store/cesium/cesiumReducer.ts, src/app.store/cesium/store.cesium.ts, src/app.store/cesium/type.ts
1. 로그인 후 '님'자 빼기
2. 로고 버튼 클릭시 초기화
=> fix something

src/app.feature/favorites/component/FavoritesTable.tsx
favorite table 에도 남은 시간 매초 렌더링 함수 적용
=> feat: favorite time rendering functions

src/app.feature/favorites/screen/Favorites.tsx, src/app.feature/favorites/style/tableStyle.ts
1. favorites 축소했을 때 테이블도 같이 사라지기
2. ㅔ이블 width 조정
=> fix: fix decrease mode and table width

src/app.feature/conjunctions/style/tableStyle.ts, src/app.feature/favorites/style/tableStyle.ts
=> style: table width change

src/app.feature/conjunctions/screen/Conjunctions.tsx, src/app.feature/favorites/screen/Favorites.tsx, src/app.modules/util/timeCounter.ts
=> fix: fix table problem

src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx, src/app.modules/cesium/drawCzml.ts, src/app.store/cesium/cesiumReducer.ts, src/app.store/cesium/store.cesium.ts
=> fix: fix names

src/app.feature/launchConjunctions/components/AssessmentModal.tsx, src/app.feature/launchConjunctions/query/useQueryLPDB.ts, src/app.modules/util/downloadHelper.ts
=>   "fix: fix lca sample download instead of new tab"

src/app.feature/watcherCatcher/components/SearchModal.tsx, src/app.feature/watcherCatcher/types/watcherCatcher.ts
watcher catcher 새로운 input 값 추가
=> feat: implement new input in watcher-catcher

src/app.feature/watcherCatcher/components/SearchModal.tsx
=> fix: check if every input value is valid

src/app.feature/launchConjunctions/components/AssessmentModal.tsx, src/app.feature/launchConjunctions/query/useQueryLPDB.ts
=> fix: fix download issue in develop

src/app.components/modal/SuccessModal.tsx, src/app.feature/launchConjunctions/components/AssessmentModal.tsx, src/app.feature/launchConjunctions/components/SuccessModal.tsx, src/app.feature/launchConjunctions/query/useMutationLPDB.ts, src/app.feature/launchConjunctions/query/useQueryLPDB.ts, src/app.feature/launchConjunctions/types/launchConjunctions.ts, src/app.feature/watcherCatcher/components/SearchModal.tsx, src/app.feature/watcherCatcher/components/SuccessModal.tsx
1) lca POST에 따른 에러 핸들링
2) watcher-catcher POST에 따른 에러 핸들링
3) watcher-catcher success modal text  변경
4) trajectory 유효성 검사
=> fix: fix lca error handling

src/app.feature/launchConjunctions/components/AssessmentModal.tsx, src/app.feature/watcherCatcher/types/watcherCatcher.ts
=> fix: fix build error

src/app.feature/launchConjunctions/components/LPDBTable.tsx, src/app.store/cesium/cesiumReducer.ts, src/app.store/cesium/store.cesium.ts, src/app.store/cesium/type.ts
=> cola : cesium세팅
